'use strict';

const CATEGORY_NAMES = {
  all:        'Todas las categorías',
  fruits:     'Frutas',
  animals:    'Animales',
  food:       'Comida',
  colors:     'Colores',
  body:       'Cuerpo humano',
  family:     'Familia',
  house:      'Casa y hogar',
  clothes:    'Ropa y moda',
  transport:  'Transporte',
  technology: 'Tecnología',
  nature:     'Naturaleza',
  sports:     'Deportes',
  emotions:   'Emociones',
  adjectives: 'Adjetivos',
  verbs:      'Verbos',
  time:       'Tiempo',
  weather:    'Tiempo atmosférico',
  places:     'Lugares',
  work:       'Trabajo',
  education:  'Educación',
  health:     'Salud',
  business:   'Negocios',
  academic:   'Académico',
  general:    'General'
};

const VOCABULARY = {
  A1: [
    // Fruits
    { word: 'apple',        translation: 'manzana',      category: 'fruits',    uk_ipa: '/ˈæp.əl/',          us_ipa: '/ˈæp.əl/' },
    { word: 'banana',       translation: 'plátano',      category: 'fruits',    uk_ipa: '/bəˈnɑː.nə/',       us_ipa: '/bəˈnæn.ə/' },
    { word: 'orange',       translation: 'naranja',      category: 'fruits',    uk_ipa: '/ˈɒr.ɪndʒ/',        us_ipa: '/ˈɔːr.ɪndʒ/' },
    { word: 'lemon',        translation: 'limón',        category: 'fruits',    uk_ipa: '/ˈlem.ən/',         us_ipa: '/ˈlem.ən/' },
    { word: 'strawberry',   translation: 'fresa',        category: 'fruits',    uk_ipa: '/ˈstrɔː.bər.i/',    us_ipa: '/ˈstrɔː.ber.i/' },
    { word: 'grape',        translation: 'uva',          category: 'fruits',    uk_ipa: '/ɡreɪp/',           us_ipa: '/ɡreɪp/' },
    { word: 'pear',         translation: 'pera',         category: 'fruits',    uk_ipa: '/peə/',             us_ipa: '/per/' },
    { word: 'cherry',       translation: 'cereza',       category: 'fruits',    uk_ipa: '/ˈtʃer.i/',         us_ipa: '/ˈtʃer.i/' },
    { word: 'mango',        translation: 'mango',        category: 'fruits',    uk_ipa: '/ˈmæŋ.ɡəʊ/',       us_ipa: '/ˈmæŋ.ɡoʊ/' },
    { word: 'watermelon',   translation: 'sandía',       category: 'fruits',    uk_ipa: '/ˈwɔː.tə.mel.ən/', us_ipa: '/ˈwɑː.t̬ɚ.mel.ən/' },
    // Animals
    { word: 'cat',          translation: 'gato',         category: 'animals',   uk_ipa: '/kæt/',             us_ipa: '/kæt/' },
    { word: 'dog',          translation: 'perro',        category: 'animals',   uk_ipa: '/dɒɡ/',             us_ipa: '/dɑːɡ/' },
    { word: 'bird',         translation: 'pájaro',       category: 'animals',   uk_ipa: '/bɜːd/',            us_ipa: '/bɝːd/' },
    { word: 'fish',         translation: 'pez',          category: 'animals',   uk_ipa: '/fɪʃ/',             us_ipa: '/fɪʃ/' },
    { word: 'horse',        translation: 'caballo',      category: 'animals',   uk_ipa: '/hɔːs/',            us_ipa: '/hɔːrs/' },
    { word: 'cow',          translation: 'vaca',         category: 'animals',   uk_ipa: '/kaʊ/',             us_ipa: '/kaʊ/' },
    { word: 'duck',         translation: 'pato',         category: 'animals',   uk_ipa: '/dʌk/',             us_ipa: '/dʌk/' },
    { word: 'rabbit',       translation: 'conejo',       category: 'animals',   uk_ipa: '/ˈræb.ɪt/',        us_ipa: '/ˈræb.ɪt/' },
    { word: 'elephant',     translation: 'elefante',     category: 'animals',   uk_ipa: '/ˈel.ɪ.fənt/',     us_ipa: '/ˈel.ɪ.fənt/' },
    { word: 'lion',         translation: 'león',         category: 'animals',   uk_ipa: '/ˈlaɪ.ən/',        us_ipa: '/ˈlaɪ.ən/' },
    { word: 'tiger',        translation: 'tigre',        category: 'animals',   uk_ipa: '/ˈtaɪ.ɡər/',       us_ipa: '/ˈtaɪ.ɡɚ/' },
    { word: 'snake',        translation: 'serpiente',    category: 'animals',   uk_ipa: '/sneɪk/',           us_ipa: '/sneɪk/' },
    // Colors
    { word: 'red',          translation: 'rojo',         category: 'colors',    uk_ipa: '/red/',             us_ipa: '/red/' },
    { word: 'blue',         translation: 'azul',         category: 'colors',    uk_ipa: '/bluː/',            us_ipa: '/bluː/' },
    { word: 'green',        translation: 'verde',        category: 'colors',    uk_ipa: '/ɡriːn/',           us_ipa: '/ɡriːn/' },
    { word: 'yellow',       translation: 'amarillo',     category: 'colors',    uk_ipa: '/ˈjel.əʊ/',        us_ipa: '/ˈjel.oʊ/' },
    { word: 'black',        translation: 'negro',        category: 'colors',    uk_ipa: '/blæk/',            us_ipa: '/blæk/' },
    { word: 'white',        translation: 'blanco',       category: 'colors',    uk_ipa: '/waɪt/',            us_ipa: '/waɪt/' },
    { word: 'pink',         translation: 'rosa',         category: 'colors',    uk_ipa: '/pɪŋk/',            us_ipa: '/pɪŋk/' },
    { word: 'brown',        translation: 'marrón',       category: 'colors',    uk_ipa: '/braʊn/',           us_ipa: '/braʊn/' },
    { word: 'purple',       translation: 'morado',       category: 'colors',    uk_ipa: '/ˈpɜː.pəl/',       us_ipa: '/ˈpɝː.pəl/' },
    { word: 'grey',         translation: 'gris',         category: 'colors',    uk_ipa: '/ɡreɪ/',            us_ipa: '/ɡreɪ/' },
    // Body
    { word: 'hand',         translation: 'mano',         category: 'body',      uk_ipa: '/hænd/',            us_ipa: '/hænd/' },
    { word: 'foot',         translation: 'pie',          category: 'body',      uk_ipa: '/fʊt/',             us_ipa: '/fʊt/' },
    { word: 'head',         translation: 'cabeza',       category: 'body',      uk_ipa: '/hed/',             us_ipa: '/hed/' },
    { word: 'eye',          translation: 'ojo',          category: 'body',      uk_ipa: '/aɪ/',              us_ipa: '/aɪ/' },
    { word: 'ear',          translation: 'oreja',        category: 'body',      uk_ipa: '/ɪə/',              us_ipa: '/ɪr/' },
    { word: 'nose',         translation: 'nariz',        category: 'body',      uk_ipa: '/nəʊz/',            us_ipa: '/noʊz/' },
    { word: 'mouth',        translation: 'boca',         category: 'body',      uk_ipa: '/maʊθ/',            us_ipa: '/maʊθ/' },
    { word: 'arm',          translation: 'brazo',        category: 'body',      uk_ipa: '/ɑːm/',             us_ipa: '/ɑːrm/' },
    { word: 'leg',          translation: 'pierna',       category: 'body',      uk_ipa: '/leɡ/',             us_ipa: '/leɡ/' },
    { word: 'hair',         translation: 'pelo',         category: 'body',      uk_ipa: '/heə/',             us_ipa: '/her/' },
    // Family
    { word: 'mother',       translation: 'madre',        category: 'family',    uk_ipa: '/ˈmʌð.ə/',         us_ipa: '/ˈmʌð.ɚ/' },
    { word: 'father',       translation: 'padre',        category: 'family',    uk_ipa: '/ˈfɑː.ðə/',        us_ipa: '/ˈfɑː.ðɚ/' },
    { word: 'brother',      translation: 'hermano',      category: 'family',    uk_ipa: '/ˈbrʌð.ə/',        us_ipa: '/ˈbrʌð.ɚ/' },
    { word: 'sister',       translation: 'hermana',      category: 'family',    uk_ipa: '/ˈsɪs.tə/',        us_ipa: '/ˈsɪs.tɚ/' },
    { word: 'baby',         translation: 'bebé',         category: 'family',    uk_ipa: '/ˈbeɪ.bi/',         us_ipa: '/ˈbeɪ.bi/' },
    { word: 'family',       translation: 'familia',      category: 'family',    uk_ipa: '/ˈfæm.ɪ.li/',      us_ipa: '/ˈfæm.ɪ.li/' },
    // House
    { word: 'house',        translation: 'casa',         category: 'house',     uk_ipa: '/haʊs/',            us_ipa: '/haʊs/' },
    { word: 'door',         translation: 'puerta',       category: 'house',     uk_ipa: '/dɔː/',             us_ipa: '/dɔːr/' },
    { word: 'window',       translation: 'ventana',      category: 'house',     uk_ipa: '/ˈwɪn.dəʊ/',       us_ipa: '/ˈwɪn.doʊ/' },
    { word: 'table',        translation: 'mesa',         category: 'house',     uk_ipa: '/ˈteɪ.bəl/',       us_ipa: '/ˈteɪ.bəl/' },
    { word: 'chair',        translation: 'silla',        category: 'house',     uk_ipa: '/tʃeə/',            us_ipa: '/tʃer/' },
    { word: 'bed',          translation: 'cama',         category: 'house',     uk_ipa: '/bed/',             us_ipa: '/bed/' },
    { word: 'kitchen',      translation: 'cocina',       category: 'house',     uk_ipa: '/ˈkɪtʃ.ɪn/',       us_ipa: '/ˈkɪtʃ.ɪn/' },
    { word: 'bathroom',     translation: 'cuarto de baño', category: 'house',   uk_ipa: '/ˈbɑːθ.rʊm/',      us_ipa: '/ˈbæθ.ruːm/' },
    // Food & Drinks
    { word: 'bread',        translation: 'pan',          category: 'food',      uk_ipa: '/bred/',            us_ipa: '/bred/' },
    { word: 'milk',         translation: 'leche',        category: 'food',      uk_ipa: '/mɪlk/',            us_ipa: '/mɪlk/' },
    { word: 'water',        translation: 'agua',         category: 'food',      uk_ipa: '/ˈwɔː.tə/',        us_ipa: '/ˈwɑː.t̬ɚ/' },
    { word: 'juice',        translation: 'zumo',         category: 'food',      uk_ipa: '/dʒuːs/',           us_ipa: '/dʒuːs/' },
    { word: 'coffee',       translation: 'café',         category: 'food',      uk_ipa: '/ˈkɒf.i/',         us_ipa: '/ˈkɑː.fi/' },
    { word: 'tea',          translation: 'té',           category: 'food',      uk_ipa: '/tiː/',             us_ipa: '/tiː/' },
    { word: 'rice',         translation: 'arroz',        category: 'food',      uk_ipa: '/raɪs/',            us_ipa: '/raɪs/' },
    { word: 'egg',          translation: 'huevo',        category: 'food',      uk_ipa: '/eɡ/',              us_ipa: '/eɡ/' },
    { word: 'meat',         translation: 'carne',        category: 'food',      uk_ipa: '/miːt/',            us_ipa: '/miːt/' },
    { word: 'cheese',       translation: 'queso',        category: 'food',      uk_ipa: '/tʃiːz/',           us_ipa: '/tʃiːz/' },
    // Verbs
    { word: 'go',           translation: 'ir',           category: 'verbs',     uk_ipa: '/ɡəʊ/',             us_ipa: '/ɡoʊ/' },
    { word: 'eat',          translation: 'comer',        category: 'verbs',     uk_ipa: '/iːt/',             us_ipa: '/iːt/' },
    { word: 'drink',        translation: 'beber',        category: 'verbs',     uk_ipa: '/drɪŋk/',           us_ipa: '/drɪŋk/' },
    { word: 'sleep',        translation: 'dormir',       category: 'verbs',     uk_ipa: '/sliːp/',           us_ipa: '/sliːp/' },
    { word: 'walk',         translation: 'caminar',      category: 'verbs',     uk_ipa: '/wɔːk/',            us_ipa: '/wɔːk/' },
    { word: 'run',          translation: 'correr',       category: 'verbs',     uk_ipa: '/rʌn/',             us_ipa: '/rʌn/' },
    { word: 'read',         translation: 'leer',         category: 'verbs',     uk_ipa: '/riːd/',            us_ipa: '/riːd/' },
    { word: 'write',        translation: 'escribir',     category: 'verbs',     uk_ipa: '/raɪt/',            us_ipa: '/raɪt/' },
    { word: 'see',          translation: 'ver',          category: 'verbs',     uk_ipa: '/siː/',             us_ipa: '/siː/' },
    { word: 'like',         translation: 'gustar',       category: 'verbs',     uk_ipa: '/laɪk/',            us_ipa: '/laɪk/' },
    // Adjectives
    { word: 'big',          translation: 'grande',       category: 'adjectives', uk_ipa: '/bɪɡ/',            us_ipa: '/bɪɡ/' },
    { word: 'small',        translation: 'pequeño',      category: 'adjectives', uk_ipa: '/smɔːl/',          us_ipa: '/smɔːl/' },
    { word: 'new',          translation: 'nuevo',        category: 'adjectives', uk_ipa: '/njuː/',           us_ipa: '/nuː/' },
    { word: 'old',          translation: 'viejo',        category: 'adjectives', uk_ipa: '/əʊld/',           us_ipa: '/oʊld/' },
    { word: 'good',         translation: 'bueno',        category: 'adjectives', uk_ipa: '/ɡʊd/',            us_ipa: '/ɡʊd/' },
    { word: 'bad',          translation: 'malo',         category: 'adjectives', uk_ipa: '/bæd/',            us_ipa: '/bæd/' },
    { word: 'happy',        translation: 'feliz',        category: 'adjectives', uk_ipa: '/ˈhæp.i/',         us_ipa: '/ˈhæp.i/' },
    { word: 'sad',          translation: 'triste',       category: 'adjectives', uk_ipa: '/sæd/',            us_ipa: '/sæd/' },
    { word: 'hot',          translation: 'caliente',     category: 'adjectives', uk_ipa: '/hɒt/',            us_ipa: '/hɑːt/' },
    { word: 'cold',         translation: 'frío',         category: 'adjectives', uk_ipa: '/kəʊld/',          us_ipa: '/koʊld/' },
  ],

  A2: [
    // Food
    { word: 'sandwich',     translation: 'sándwich',     category: 'food',      uk_ipa: '/ˈsænd.wɪtʃ/',    us_ipa: '/ˈsænd.wɪtʃ/' },
    { word: 'salad',        translation: 'ensalada',     category: 'food',      uk_ipa: '/ˈsæl.əd/',        us_ipa: '/ˈsæl.əd/' },
    { word: 'soup',         translation: 'sopa',         category: 'food',      uk_ipa: '/suːp/',            us_ipa: '/suːp/' },
    { word: 'pizza',        translation: 'pizza',        category: 'food',      uk_ipa: '/ˈpiːt.sə/',       us_ipa: '/ˈpiːt.sə/' },
    { word: 'cake',         translation: 'pastel',       category: 'food',      uk_ipa: '/keɪk/',            us_ipa: '/keɪk/' },
    { word: 'cookie',       translation: 'galleta',      category: 'food',      uk_ipa: '/ˈkʊk.i/',         us_ipa: '/ˈkʊk.i/' },
    { word: 'yogurt',       translation: 'yogur',        category: 'food',      uk_ipa: '/ˈjɒɡ.ət/',        us_ipa: '/ˈjoʊ.ɡɚt/' },
    { word: 'butter',       translation: 'mantequilla',  category: 'food',      uk_ipa: '/ˈbʌt.ə/',         us_ipa: '/ˈbʌt̬.ɚ/' },
    { word: 'sugar',        translation: 'azúcar',       category: 'food',      uk_ipa: '/ˈʃʊɡ.ə/',         us_ipa: '/ˈʃʊɡ.ɚ/' },
    { word: 'salt',         translation: 'sal',          category: 'food',      uk_ipa: '/sɔːlt/',           us_ipa: '/sɔːlt/' },
    // Transport
    { word: 'car',          translation: 'coche',        category: 'transport', uk_ipa: '/kɑː/',             us_ipa: '/kɑːr/' },
    { word: 'bus',          translation: 'autobús',      category: 'transport', uk_ipa: '/bʌs/',             us_ipa: '/bʌs/' },
    { word: 'train',        translation: 'tren',         category: 'transport', uk_ipa: '/treɪn/',           us_ipa: '/treɪn/' },
    { word: 'plane',        translation: 'avión',        category: 'transport', uk_ipa: '/pleɪn/',           us_ipa: '/pleɪn/' },
    { word: 'bicycle',      translation: 'bicicleta',    category: 'transport', uk_ipa: '/ˈbaɪ.sɪ.kəl/',    us_ipa: '/ˈbaɪ.sɪ.kəl/' },
    { word: 'taxi',         translation: 'taxi',         category: 'transport', uk_ipa: '/ˈtæk.si/',         us_ipa: '/ˈtæk.si/' },
    { word: 'boat',         translation: 'barco',        category: 'transport', uk_ipa: '/bəʊt/',            us_ipa: '/boʊt/' },
    { word: 'subway',       translation: 'metro',        category: 'transport', uk_ipa: '/ˈsʌb.weɪ/',       us_ipa: '/ˈsʌb.weɪ/' },
    // Places
    { word: 'school',       translation: 'colegio',      category: 'places',    uk_ipa: '/skuːl/',           us_ipa: '/skuːl/' },
    { word: 'hospital',     translation: 'hospital',     category: 'places',    uk_ipa: '/ˈhɒs.pɪ.tl/',     us_ipa: '/ˈhɑːs.pɪ.t̬əl/' },
    { word: 'park',         translation: 'parque',       category: 'places',    uk_ipa: '/pɑːk/',            us_ipa: '/pɑːrk/' },
    { word: 'market',       translation: 'mercado',      category: 'places',    uk_ipa: '/ˈmɑː.kɪt/',       us_ipa: '/ˈmɑːr.kɪt/' },
    { word: 'cinema',       translation: 'cine',         category: 'places',    uk_ipa: '/ˈsɪn.ɪ.mə/',      us_ipa: '/ˈsɪn.ɪ.mə/' },
    { word: 'bank',         translation: 'banco',        category: 'places',    uk_ipa: '/bæŋk/',            us_ipa: '/bæŋk/' },
    { word: 'hotel',        translation: 'hotel',        category: 'places',    uk_ipa: '/həʊˈtel/',         us_ipa: '/hoʊˈtel/' },
    { word: 'library',      translation: 'biblioteca',   category: 'places',    uk_ipa: '/ˈlaɪ.brər.i/',    us_ipa: '/ˈlaɪ.brer.i/' },
    // Adjectives
    { word: 'beautiful',    translation: 'hermoso',      category: 'adjectives', uk_ipa: '/ˈbjuː.tɪ.fəl/',  us_ipa: '/ˈbjuː.t̬ɪ.fəl/' },
    { word: 'clean',        translation: 'limpio',       category: 'adjectives', uk_ipa: '/kliːn/',          us_ipa: '/kliːn/' },
    { word: 'dirty',        translation: 'sucio',        category: 'adjectives', uk_ipa: '/ˈdɜː.ti/',        us_ipa: '/ˈdɝː.t̬i/' },
    { word: 'easy',         translation: 'fácil',        category: 'adjectives', uk_ipa: '/ˈiː.zi/',         us_ipa: '/ˈiː.zi/' },
    { word: 'difficult',    translation: 'difícil',      category: 'adjectives', uk_ipa: '/ˈdɪf.ɪ.kəlt/',   us_ipa: '/ˈdɪf.ɪ.kəlt/' },
    { word: 'fast',         translation: 'rápido',       category: 'adjectives', uk_ipa: '/fɑːst/',          us_ipa: '/fæst/' },
    { word: 'slow',         translation: 'lento',        category: 'adjectives', uk_ipa: '/sləʊ/',           us_ipa: '/sloʊ/' },
    { word: 'young',        translation: 'joven',        category: 'adjectives', uk_ipa: '/jʌŋ/',            us_ipa: '/jʌŋ/' },
    { word: 'tired',        translation: 'cansado',      category: 'adjectives', uk_ipa: '/ˈtaɪəd/',         us_ipa: '/ˈtaɪɚd/' },
    { word: 'angry',        translation: 'enfadado',     category: 'adjectives', uk_ipa: '/ˈæŋ.ɡri/',        us_ipa: '/ˈæŋ.ɡri/' },
    // Verbs
    { word: 'arrive',       translation: 'llegar',       category: 'verbs',     uk_ipa: '/əˈraɪv/',          us_ipa: '/əˈraɪv/' },
    { word: 'buy',          translation: 'comprar',      category: 'verbs',     uk_ipa: '/baɪ/',             us_ipa: '/baɪ/' },
    { word: 'call',         translation: 'llamar',       category: 'verbs',     uk_ipa: '/kɔːl/',            us_ipa: '/kɔːl/' },
    { word: 'cook',         translation: 'cocinar',      category: 'verbs',     uk_ipa: '/kʊk/',             us_ipa: '/kʊk/' },
    { word: 'decide',       translation: 'decidir',      category: 'verbs',     uk_ipa: '/dɪˈsaɪd/',        us_ipa: '/dɪˈsaɪd/' },
    { word: 'drive',        translation: 'conducir',     category: 'verbs',     uk_ipa: '/draɪv/',           us_ipa: '/draɪv/' },
    { word: 'forget',       translation: 'olvidar',      category: 'verbs',     uk_ipa: '/fəˈɡet/',          us_ipa: '/fɚˈɡet/' },
    { word: 'help',         translation: 'ayudar',       category: 'verbs',     uk_ipa: '/help/',            us_ipa: '/help/' },
    { word: 'know',         translation: 'saber / conocer', category: 'verbs',  uk_ipa: '/nəʊ/',             us_ipa: '/noʊ/' },
    { word: 'learn',        translation: 'aprender',     category: 'verbs',     uk_ipa: '/lɜːn/',            us_ipa: '/lɝːn/' },
    { word: 'meet',         translation: 'conocer',      category: 'verbs',     uk_ipa: '/miːt/',            us_ipa: '/miːt/' },
    { word: 'pay',          translation: 'pagar',        category: 'verbs',     uk_ipa: '/peɪ/',             us_ipa: '/peɪ/' },
    { word: 'stay',         translation: 'quedarse',     category: 'verbs',     uk_ipa: '/steɪ/',            us_ipa: '/steɪ/' },
    { word: 'tell',         translation: 'decir',        category: 'verbs',     uk_ipa: '/tel/',             us_ipa: '/tel/' },
    { word: 'watch',        translation: 'mirar',        category: 'verbs',     uk_ipa: '/wɒtʃ/',            us_ipa: '/wɑːtʃ/' },
    // Time
    { word: 'today',        translation: 'hoy',          category: 'time',      uk_ipa: '/təˈdeɪ/',          us_ipa: '/təˈdeɪ/' },
    { word: 'tomorrow',     translation: 'mañana',       category: 'time',      uk_ipa: '/təˈmɒr.əʊ/',      us_ipa: '/təˈmɑːr.oʊ/' },
    { word: 'yesterday',    translation: 'ayer',         category: 'time',      uk_ipa: '/ˈjes.tə.deɪ/',    us_ipa: '/ˈjes.tɚ.deɪ/' },
    { word: 'week',         translation: 'semana',       category: 'time',      uk_ipa: '/wiːk/',            us_ipa: '/wiːk/' },
    { word: 'month',        translation: 'mes',          category: 'time',      uk_ipa: '/mʌnθ/',            us_ipa: '/mʌnθ/' },
    { word: 'year',         translation: 'año',          category: 'time',      uk_ipa: '/jɪə/',             us_ipa: '/jɪr/' },
    // Weather
    { word: 'sun',          translation: 'sol',          category: 'weather',   uk_ipa: '/sʌn/',             us_ipa: '/sʌn/' },
    { word: 'rain',         translation: 'lluvia',       category: 'weather',   uk_ipa: '/reɪn/',            us_ipa: '/reɪn/' },
    { word: 'snow',         translation: 'nieve',        category: 'weather',   uk_ipa: '/snəʊ/',            us_ipa: '/snoʊ/' },
    { word: 'wind',         translation: 'viento',       category: 'weather',   uk_ipa: '/wɪnd/',            us_ipa: '/wɪnd/' },
    { word: 'cloud',        translation: 'nube',         category: 'weather',   uk_ipa: '/klaʊd/',           us_ipa: '/klaʊd/' },
    { word: 'warm',         translation: 'cálido',       category: 'weather',   uk_ipa: '/wɔːm/',            us_ipa: '/wɔːrm/' },
    { word: 'cool',         translation: 'fresco',       category: 'weather',   uk_ipa: '/kuːl/',            us_ipa: '/kuːl/' },
    // Clothes
    { word: 'shirt',        translation: 'camisa',       category: 'clothes',   uk_ipa: '/ʃɜːt/',            us_ipa: '/ʃɝːt/' },
    { word: 'shoes',        translation: 'zapatos',      category: 'clothes',   uk_ipa: '/ʃuːz/',            us_ipa: '/ʃuːz/' },
    { word: 'hat',          translation: 'sombrero',     category: 'clothes',   uk_ipa: '/hæt/',             us_ipa: '/hæt/' },
    { word: 'dress',        translation: 'vestido',      category: 'clothes',   uk_ipa: '/dres/',            us_ipa: '/dres/' },
    { word: 'jacket',       translation: 'chaqueta',     category: 'clothes',   uk_ipa: '/ˈdʒæk.ɪt/',       us_ipa: '/ˈdʒæk.ɪt/' },
    { word: 'trousers',     translation: 'pantalones',   category: 'clothes',   uk_ipa: '/ˈtraʊ.zəz/',      us_ipa: '/ˈtraʊ.zɚz/' },
    { word: 'socks',        translation: 'calcetines',   category: 'clothes',   uk_ipa: '/sɒks/',            us_ipa: '/sɑːks/' },
  ],

  B1: [
    // Work
    { word: 'career',       translation: 'carrera',      category: 'work',      uk_ipa: '/kəˈrɪə/',          us_ipa: '/kəˈrɪr/' },
    { word: 'colleague',    translation: 'colega',       category: 'work',      uk_ipa: '/ˈkɒl.iːɡ/',       us_ipa: '/ˈkɑː.liːɡ/' },
    { word: 'company',      translation: 'empresa',      category: 'work',      uk_ipa: '/ˈkʌm.pə.ni/',     us_ipa: '/ˈkʌm.pə.ni/' },
    { word: 'employee',     translation: 'empleado',     category: 'work',      uk_ipa: '/ɪmˈplɔɪ.iː/',     us_ipa: '/ɪmˈplɔɪ.iː/' },
    { word: 'employer',     translation: 'empleador',    category: 'work',      uk_ipa: '/ɪmˈplɔɪ.ər/',     us_ipa: '/ɪmˈplɔɪ.ɚ/' },
    { word: 'interview',    translation: 'entrevista',   category: 'work',      uk_ipa: '/ˈɪn.tə.vjuː/',    us_ipa: '/ˈɪn.t̬ɚ.vjuː/' },
    { word: 'manager',      translation: 'gerente',      category: 'work',      uk_ipa: '/ˈmæn.ɪ.dʒər/',    us_ipa: '/ˈmæn.ɪ.dʒɚ/' },
    { word: 'meeting',      translation: 'reunión',      category: 'work',      uk_ipa: '/ˈmiː.tɪŋ/',       us_ipa: '/ˈmiː.t̬ɪŋ/' },
    { word: 'office',       translation: 'oficina',      category: 'work',      uk_ipa: '/ˈɒf.ɪs/',         us_ipa: '/ˈɑː.fɪs/' },
    { word: 'salary',       translation: 'salario',      category: 'work',      uk_ipa: '/ˈsæl.ər.i/',      us_ipa: '/ˈsæl.ɚ.i/' },
    // Health
    { word: 'appointment',  translation: 'cita médica',  category: 'health',    uk_ipa: '/əˈpɔɪnt.mənt/',   us_ipa: '/əˈpɔɪnt.mənt/' },
    { word: 'disease',      translation: 'enfermedad',   category: 'health',    uk_ipa: '/dɪˈziːz/',         us_ipa: '/dɪˈziːz/' },
    { word: 'exercise',     translation: 'ejercicio',    category: 'health',    uk_ipa: '/ˈek.sə.saɪz/',    us_ipa: '/ˈek.sɚ.saɪz/' },
    { word: 'healthy',      translation: 'saludable',    category: 'health',    uk_ipa: '/ˈhel.θi/',         us_ipa: '/ˈhel.θi/' },
    { word: 'illness',      translation: 'dolencia',     category: 'health',    uk_ipa: '/ˈɪl.nəs/',         us_ipa: '/ˈɪl.nəs/' },
    { word: 'medicine',     translation: 'medicina',     category: 'health',    uk_ipa: '/ˈmed.sɪn/',        us_ipa: '/ˈmed.sɪn/' },
    { word: 'patient',      translation: 'paciente',     category: 'health',    uk_ipa: '/ˈpeɪ.ʃənt/',      us_ipa: '/ˈpeɪ.ʃənt/' },
    { word: 'treatment',    translation: 'tratamiento',  category: 'health',    uk_ipa: '/ˈtriːt.mənt/',    us_ipa: '/ˈtriːt.mənt/' },
    // Emotions
    { word: 'confident',    translation: 'seguro de sí mismo', category: 'emotions', uk_ipa: '/ˈkɒn.fɪ.dənt/', us_ipa: '/ˈkɑːn.fɪ.dənt/' },
    { word: 'curious',      translation: 'curioso',      category: 'emotions',  uk_ipa: '/ˈkjʊər.i.əs/',    us_ipa: '/ˈkjʊr.i.əs/' },
    { word: 'disappointed', translation: 'decepcionado', category: 'emotions',  uk_ipa: '/ˌdɪs.əˈpɔɪn.tɪd/', us_ipa: '/ˌdɪs.əˈpɔɪn.t̬ɪd/' },
    { word: 'excited',      translation: 'emocionado',   category: 'emotions',  uk_ipa: '/ɪkˈsaɪ.tɪd/',     us_ipa: '/ɪkˈsaɪ.t̬ɪd/' },
    { word: 'nervous',      translation: 'nervioso',     category: 'emotions',  uk_ipa: '/ˈnɜː.vəs/',        us_ipa: '/ˈnɝː.vəs/' },
    { word: 'proud',        translation: 'orgulloso',    category: 'emotions',  uk_ipa: '/praʊd/',           us_ipa: '/praʊd/' },
    { word: 'relaxed',      translation: 'relajado',     category: 'emotions',  uk_ipa: '/rɪˈlækst/',        us_ipa: '/rɪˈlækst/' },
    { word: 'worried',      translation: 'preocupado',   category: 'emotions',  uk_ipa: '/ˈwʌr.id/',         us_ipa: '/ˈwɝː.id/' },
    // Education
    { word: 'essay',        translation: 'redacción',    category: 'education', uk_ipa: '/ˈes.eɪ/',          us_ipa: '/ˈes.eɪ/' },
    { word: 'exam',         translation: 'examen',       category: 'education', uk_ipa: '/ɪɡˈzæm/',          us_ipa: '/ɪɡˈzæm/' },
    { word: 'grade',        translation: 'nota',         category: 'education', uk_ipa: '/ɡreɪd/',           us_ipa: '/ɡreɪd/' },
    { word: 'knowledge',    translation: 'conocimiento', category: 'education', uk_ipa: '/ˈnɒl.ɪdʒ/',        us_ipa: '/ˈnɑː.lɪdʒ/' },
    { word: 'lesson',       translation: 'lección',      category: 'education', uk_ipa: '/ˈles.ən/',         us_ipa: '/ˈles.ən/' },
    { word: 'research',     translation: 'investigación', category: 'education', uk_ipa: '/rɪˈsɜːtʃ/',       us_ipa: '/rɪˈsɝːtʃ/' },
    { word: 'subject',      translation: 'asignatura',   category: 'education', uk_ipa: '/ˈsʌb.dʒɪkt/',     us_ipa: '/ˈsʌb.dʒɪkt/' },
    // Technology
    { word: 'computer',     translation: 'ordenador',    category: 'technology', uk_ipa: '/kəmˈpjuː.tər/', us_ipa: '/kəmˈpjuː.t̬ɚ/' },
    { word: 'email',        translation: 'correo electrónico', category: 'technology', uk_ipa: '/ˈiː.meɪl/', us_ipa: '/ˈiː.meɪl/' },
    { word: 'internet',     translation: 'internet',     category: 'technology', uk_ipa: '/ˈɪn.tə.net/',    us_ipa: '/ˈɪn.t̬ɚ.net/' },
    { word: 'message',      translation: 'mensaje',      category: 'technology', uk_ipa: '/ˈmes.ɪdʒ/',      us_ipa: '/ˈmes.ɪdʒ/' },
    { word: 'password',     translation: 'contraseña',   category: 'technology', uk_ipa: '/ˈpɑːs.wɜːd/',    us_ipa: '/ˈpæs.wɝːd/' },
    { word: 'screen',       translation: 'pantalla',     category: 'technology', uk_ipa: '/skriːn/',         us_ipa: '/skriːn/' },
    { word: 'website',      translation: 'sitio web',    category: 'technology', uk_ipa: '/ˈweb.saɪt/',     us_ipa: '/ˈweb.saɪt/' },
    // Verbs
    { word: 'achieve',      translation: 'lograr',       category: 'verbs',     uk_ipa: '/əˈtʃiːv/',         us_ipa: '/əˈtʃiːv/' },
    { word: 'affect',       translation: 'afectar',      category: 'verbs',     uk_ipa: '/əˈfekt/',          us_ipa: '/əˈfekt/' },
    { word: 'allow',        translation: 'permitir',     category: 'verbs',     uk_ipa: '/əˈlaʊ/',           us_ipa: '/əˈlaʊ/' },
    { word: 'apply',        translation: 'solicitar',    category: 'verbs',     uk_ipa: '/əˈplaɪ/',          us_ipa: '/əˈplaɪ/' },
    { word: 'avoid',        translation: 'evitar',       category: 'verbs',     uk_ipa: '/əˈvɔɪd/',          us_ipa: '/əˈvɔɪd/' },
    { word: 'challenge',    translation: 'desafiar',     category: 'verbs',     uk_ipa: '/ˈtʃæl.ɪndʒ/',     us_ipa: '/ˈtʃæl.ɪndʒ/' },
    { word: 'compare',      translation: 'comparar',     category: 'verbs',     uk_ipa: '/kəmˈpeə/',         us_ipa: '/kəmˈper/' },
    { word: 'describe',     translation: 'describir',    category: 'verbs',     uk_ipa: '/dɪˈskraɪb/',       us_ipa: '/dɪˈskraɪb/' },
    { word: 'develop',      translation: 'desarrollar',  category: 'verbs',     uk_ipa: '/dɪˈvel.əp/',       us_ipa: '/dɪˈvel.əp/' },
    { word: 'discuss',      translation: 'discutir',     category: 'verbs',     uk_ipa: '/dɪˈskʌs/',         us_ipa: '/dɪˈskʌs/' },
    { word: 'explain',      translation: 'explicar',     category: 'verbs',     uk_ipa: '/ɪkˈspleɪn/',       us_ipa: '/ɪkˈspleɪn/' },
    { word: 'improve',      translation: 'mejorar',      category: 'verbs',     uk_ipa: '/ɪmˈpruːv/',        us_ipa: '/ɪmˈpruːv/' },
    { word: 'suggest',      translation: 'sugerir',      category: 'verbs',     uk_ipa: '/səˈdʒest/',        us_ipa: '/səˈdʒest/' },
    // Abstract nouns
    { word: 'advantage',    translation: 'ventaja',      category: 'general',   uk_ipa: '/ədˈvɑːn.tɪdʒ/',   us_ipa: '/ədˈvæn.t̬ɪdʒ/' },
    { word: 'behavior',     translation: 'comportamiento', category: 'general', uk_ipa: '/bɪˈheɪ.vjər/',    us_ipa: '/bɪˈheɪ.vjɚ/' },
    { word: 'choice',       translation: 'elección',     category: 'general',   uk_ipa: '/tʃɔɪs/',           us_ipa: '/tʃɔɪs/' },
    { word: 'effort',       translation: 'esfuerzo',     category: 'general',   uk_ipa: '/ˈef.ət/',          us_ipa: '/ˈef.ɚt/' },
    { word: 'experience',   translation: 'experiencia',  category: 'general',   uk_ipa: '/ɪkˈspɪər.i.əns/', us_ipa: '/ɪkˈspɪr.i.əns/' },
    { word: 'failure',      translation: 'fracaso',      category: 'general',   uk_ipa: '/ˈfeɪ.ljər/',       us_ipa: '/ˈfeɪ.ljɚ/' },
    { word: 'growth',       translation: 'crecimiento',  category: 'general',   uk_ipa: '/ɡrəʊθ/',           us_ipa: '/ɡroʊθ/' },
  ],

  B2: [
    // Abstract
    { word: 'analysis',     translation: 'análisis',     category: 'academic',  uk_ipa: '/əˈnæl.ɪ.sɪs/',    us_ipa: '/əˈnæl.ɪ.sɪs/' },
    { word: 'approach',     translation: 'enfoque',      category: 'academic',  uk_ipa: '/əˈprəʊtʃ/',        us_ipa: '/əˈproʊtʃ/' },
    { word: 'assessment',   translation: 'evaluación',   category: 'education', uk_ipa: '/əˈses.mənt/',      us_ipa: '/əˈses.mənt/' },
    { word: 'attitude',     translation: 'actitud',      category: 'general',   uk_ipa: '/ˈæt.ɪ.tjuːd/',    us_ipa: '/ˈæt̬.ɪ.tuːd/' },
    { word: 'commitment',   translation: 'compromiso',   category: 'general',   uk_ipa: '/kəˈmɪt.mənt/',    us_ipa: '/kəˈmɪt.mənt/' },
    { word: 'consequence',  translation: 'consecuencia', category: 'general',   uk_ipa: '/ˈkɒn.sɪ.kwəns/',  us_ipa: '/ˈkɑːn.sɪ.kwəns/' },
    { word: 'evidence',     translation: 'evidencia',    category: 'academic',  uk_ipa: '/ˈev.ɪ.dəns/',     us_ipa: '/ˈev.ɪ.dəns/' },
    { word: 'impact',       translation: 'impacto',      category: 'general',   uk_ipa: '/ˈɪm.pækt/',       us_ipa: '/ˈɪm.pækt/' },
    { word: 'perspective',  translation: 'perspectiva',  category: 'general',   uk_ipa: '/pəˈspek.tɪv/',    us_ipa: '/pɚˈspek.tɪv/' },
    { word: 'strategy',     translation: 'estrategia',   category: 'business',  uk_ipa: '/ˈstræt.ɪ.dʒi/',   us_ipa: '/ˈstræt̬.ɪ.dʒi/' },
    // Academic
    { word: 'concept',      translation: 'concepto',     category: 'academic',  uk_ipa: '/ˈkɒn.sept/',      us_ipa: '/ˈkɑːn.sept/' },
    { word: 'context',      translation: 'contexto',     category: 'academic',  uk_ipa: '/ˈkɒn.tekst/',     us_ipa: '/ˈkɑːn.tekst/' },
    { word: 'factor',       translation: 'factor',       category: 'academic',  uk_ipa: '/ˈfæk.tər/',       us_ipa: '/ˈfæk.tɚ/' },
    { word: 'framework',    translation: 'marco',        category: 'academic',  uk_ipa: '/ˈfreɪm.wɜːk/',    us_ipa: '/ˈfreɪm.wɝːk/' },
    { word: 'hypothesis',   translation: 'hipótesis',    category: 'academic',  uk_ipa: '/haɪˈpɒθ.ɪ.sɪs/', us_ipa: '/haɪˈpɑː.θɪ.sɪs/' },
    { word: 'principle',    translation: 'principio',    category: 'academic',  uk_ipa: '/ˈprɪn.sɪ.pəl/',   us_ipa: '/ˈprɪn.sɪ.pəl/' },
    { word: 'process',      translation: 'proceso',      category: 'academic',  uk_ipa: '/ˈprəʊ.ses/',      us_ipa: '/ˈprɑː.ses/' },
    { word: 'structure',    translation: 'estructura',   category: 'academic',  uk_ipa: '/ˈstrʌk.tʃər/',    us_ipa: '/ˈstrʌk.tʃɚ/' },
    { word: 'theory',       translation: 'teoría',       category: 'academic',  uk_ipa: '/ˈθɪər.i/',        us_ipa: '/ˈθɪr.i/' },
    // Adjectives
    { word: 'accurate',     translation: 'preciso',      category: 'adjectives', uk_ipa: '/ˈæk.jʊ.rət/',    us_ipa: '/ˈæk.jʊ.rət/' },
    { word: 'adequate',     translation: 'adecuado',     category: 'adjectives', uk_ipa: '/ˈæd.ɪ.kwət/',    us_ipa: '/ˈæd.ɪ.kwət/' },
    { word: 'comprehensive', translation: 'exhaustivo',  category: 'adjectives', uk_ipa: '/ˌkɒm.prɪˈhen.sɪv/', us_ipa: '/ˌkɑːm.prɪˈhen.sɪv/' },
    { word: 'controversial', translation: 'controvertido', category: 'adjectives', uk_ipa: '/ˌkɒn.trəˈvɜː.ʃəl/', us_ipa: '/ˌkɑːn.trəˈvɝː.ʃəl/' },
    { word: 'crucial',      translation: 'crucial',      category: 'adjectives', uk_ipa: '/ˈkruː.ʃəl/',     us_ipa: '/ˈkruː.ʃəl/' },
    { word: 'efficient',    translation: 'eficiente',    category: 'adjectives', uk_ipa: '/ɪˈfɪʃ.ənt/',     us_ipa: '/ɪˈfɪʃ.ənt/' },
    { word: 'fundamental',  translation: 'fundamental',  category: 'adjectives', uk_ipa: '/ˌfʌn.dəˈmen.tl/', us_ipa: '/ˌfʌn.dəˈmen.t̬l/' },
    { word: 'genuine',      translation: 'genuino',      category: 'adjectives', uk_ipa: '/ˈdʒen.ju.ɪn/',   us_ipa: '/ˈdʒen.ju.ɪn/' },
    { word: 'inevitable',   translation: 'inevitable',   category: 'adjectives', uk_ipa: '/ɪnˈev.ɪ.tə.bəl/', us_ipa: '/ɪnˈev.ɪ.t̬ə.bəl/' },
    { word: 'innovative',   translation: 'innovador',    category: 'adjectives', uk_ipa: '/ˈɪn.ə.veɪ.tɪv/', us_ipa: '/ˈɪn.ə.veɪ.t̬ɪv/' },
    { word: 'logical',      translation: 'lógico',       category: 'adjectives', uk_ipa: '/ˈlɒdʒ.ɪ.kəl/',   us_ipa: '/ˈlɑː.dʒɪ.kəl/' },
    { word: 'relevant',     translation: 'relevante',    category: 'adjectives', uk_ipa: '/ˈrel.ɪ.vənt/',   us_ipa: '/ˈrel.ɪ.vənt/' },
    { word: 'significant',  translation: 'significativo', category: 'adjectives', uk_ipa: '/sɪɡˈnɪf.ɪ.kənt/', us_ipa: '/sɪɡˈnɪf.ɪ.kənt/' },
    { word: 'sophisticated', translation: 'sofisticado', category: 'adjectives', uk_ipa: '/səˈfɪs.tɪ.keɪ.tɪd/', us_ipa: '/səˈfɪs.tɪ.keɪ.t̬ɪd/' },
    { word: 'transparent',  translation: 'transparente', category: 'adjectives', uk_ipa: '/trænsˈpær.ənt/',  us_ipa: '/trænsˈper.ənt/' },
    // Verbs
    { word: 'acknowledge',  translation: 'reconocer',    category: 'verbs',     uk_ipa: '/əkˈnɒl.ɪdʒ/',     us_ipa: '/əkˈnɑː.lɪdʒ/' },
    { word: 'anticipate',   translation: 'anticipar',    category: 'verbs',     uk_ipa: '/ænˈtɪs.ɪ.peɪt/',  us_ipa: '/ænˈtɪs.ɪ.peɪt/' },
    { word: 'demonstrate',  translation: 'demostrar',    category: 'verbs',     uk_ipa: '/ˈdem.ən.streɪt/', us_ipa: '/ˈdem.ən.streɪt/' },
    { word: 'evaluate',     translation: 'evaluar',      category: 'verbs',     uk_ipa: '/ɪˈvæl.ju.eɪt/',   us_ipa: '/ɪˈvæl.ju.eɪt/' },
    { word: 'implement',    translation: 'implementar',  category: 'verbs',     uk_ipa: '/ˈɪm.plɪ.ment/',   us_ipa: '/ˈɪm.plɪ.ment/' },
    { word: 'indicate',     translation: 'indicar',      category: 'verbs',     uk_ipa: '/ˈɪn.dɪ.keɪt/',    us_ipa: '/ˈɪn.dɪ.keɪt/' },
    { word: 'negotiate',    translation: 'negociar',     category: 'verbs',     uk_ipa: '/nɪˈɡəʊ.ʃi.eɪt/', us_ipa: '/nɪˈɡoʊ.ʃi.eɪt/' },
    // Business
    { word: 'budget',       translation: 'presupuesto',  category: 'business',  uk_ipa: '/ˈbʌdʒ.ɪt/',       us_ipa: '/ˈbʌdʒ.ɪt/' },
    { word: 'client',       translation: 'cliente',      category: 'business',  uk_ipa: '/ˈklaɪ.ənt/',      us_ipa: '/ˈklaɪ.ənt/' },
    { word: 'competition',  translation: 'competencia',  category: 'business',  uk_ipa: '/ˌkɒm.pɪˈtɪʃ.ən/', us_ipa: '/ˌkɑːm.pɪˈtɪʃ.ən/' },
    { word: 'contract',     translation: 'contrato',     category: 'business',  uk_ipa: '/ˈkɒn.trækt/',     us_ipa: '/ˈkɑːn.trækt/' },
    { word: 'investment',   translation: 'inversión',    category: 'business',  uk_ipa: '/ɪnˈvest.mənt/',   us_ipa: '/ɪnˈvest.mənt/' },
    { word: 'profit',       translation: 'beneficio',    category: 'business',  uk_ipa: '/ˈprɒf.ɪt/',       us_ipa: '/ˈprɑː.fɪt/' },
    { word: 'revenue',      translation: 'ingresos',     category: 'business',  uk_ipa: '/ˈrev.ɪ.njuː/',    us_ipa: '/ˈrev.ɪ.njuː/' },
    { word: 'supply',       translation: 'suministro',   category: 'business',  uk_ipa: '/səˈplaɪ/',         us_ipa: '/səˈplaɪ/' },
    { word: 'trade',        translation: 'comercio',     category: 'business',  uk_ipa: '/treɪd/',           us_ipa: '/treɪd/' },
    { word: 'demand',       translation: 'demanda',      category: 'business',  uk_ipa: '/dɪˈmɑːnd/',        us_ipa: '/dɪˈmænd/' },
  ],

  C1: [
    // Advanced verbs
    { word: 'alleviate',    translation: 'aliviar',      category: 'verbs',     uk_ipa: '/əˈliː.vi.eɪt/',   us_ipa: '/əˈliː.vi.eɪt/' },
    { word: 'articulate',   translation: 'articular',    category: 'verbs',     uk_ipa: '/ɑːˈtɪk.jʊ.leɪt/', us_ipa: '/ɑːrˈtɪk.jʊ.leɪt/' },
    { word: 'assimilate',   translation: 'asimilar',     category: 'verbs',     uk_ipa: '/əˈsɪm.ɪ.leɪt/',   us_ipa: '/əˈsɪm.ɪ.leɪt/' },
    { word: 'consolidate',  translation: 'consolidar',   category: 'verbs',     uk_ipa: '/kənˈsɒl.ɪ.deɪt/', us_ipa: '/kənˈsɑː.lɪ.deɪt/' },
    { word: 'contemplate',  translation: 'contemplar',   category: 'verbs',     uk_ipa: '/ˈkɒn.tem.pleɪt/', us_ipa: '/ˈkɑːn.t̬em.pleɪt/' },
    { word: 'convey',       translation: 'transmitir',   category: 'verbs',     uk_ipa: '/kənˈveɪ/',         us_ipa: '/kənˈveɪ/' },
    { word: 'cultivate',    translation: 'cultivar',     category: 'verbs',     uk_ipa: '/ˈkʌl.tɪ.veɪt/',   us_ipa: '/ˈkʌl.tɪ.veɪt/' },
    { word: 'elaborate',    translation: 'elaborar',     category: 'verbs',     uk_ipa: '/ɪˈlæb.ər.eɪt/',   us_ipa: '/ɪˈlæb.ɚ.eɪt/' },
    { word: 'facilitate',   translation: 'facilitar',    category: 'verbs',     uk_ipa: '/fəˈsɪl.ɪ.teɪt/',  us_ipa: '/fəˈsɪl.ɪ.teɪt/' },
    { word: 'formulate',    translation: 'formular',     category: 'verbs',     uk_ipa: '/ˈfɔː.mjʊ.leɪt/',  us_ipa: '/ˈfɔːr.mjʊ.leɪt/' },
    { word: 'integrate',    translation: 'integrar',     category: 'verbs',     uk_ipa: '/ˈɪn.tɪ.ɡreɪt/',   us_ipa: '/ˈɪn.tɪ.ɡreɪt/' },
    { word: 'scrutinize',   translation: 'escudriñar',   category: 'verbs',     uk_ipa: '/ˈskruː.tɪ.naɪz/', us_ipa: '/ˈskruː.tɪ.naɪz/' },
    { word: 'synthesize',   translation: 'sintetizar',   category: 'verbs',     uk_ipa: '/ˈsɪn.θɪ.saɪz/',   us_ipa: '/ˈsɪn.θɪ.saɪz/' },
    { word: 'validate',     translation: 'validar',      category: 'verbs',     uk_ipa: '/ˈvæl.ɪ.deɪt/',    us_ipa: '/ˈvæl.ɪ.deɪt/' },
    { word: 'empower',      translation: 'empoderar',    category: 'verbs',     uk_ipa: '/ɪmˈpaʊ.ər/',       us_ipa: '/ɪmˈpaʊ.ɚ/' },
    // Advanced adjectives
    { word: 'ambiguous',    translation: 'ambiguo',      category: 'adjectives', uk_ipa: '/æmˈbɪɡ.ju.əs/',  us_ipa: '/æmˈbɪɡ.ju.əs/' },
    { word: 'apprehensive', translation: 'aprensivo',    category: 'adjectives', uk_ipa: '/ˌæp.rɪˈhen.sɪv/', us_ipa: '/ˌæp.rɪˈhen.sɪv/' },
    { word: 'autonomous',   translation: 'autónomo',     category: 'adjectives', uk_ipa: '/ɔːˈtɒn.ə.məs/',  us_ipa: '/ɔːˈtɑː.nə.məs/' },
    { word: 'coherent',     translation: 'coherente',    category: 'adjectives', uk_ipa: '/kəʊˈhɪər.ənt/',   us_ipa: '/koʊˈhɪr.ənt/' },
    { word: 'compelling',   translation: 'convincente',  category: 'adjectives', uk_ipa: '/kəmˈpel.ɪŋ/',    us_ipa: '/kəmˈpel.ɪŋ/' },
    { word: 'concise',      translation: 'conciso',      category: 'adjectives', uk_ipa: '/kənˈsaɪs/',       us_ipa: '/kənˈsaɪs/' },
    { word: 'cumulative',   translation: 'acumulativo',  category: 'adjectives', uk_ipa: '/ˈkjuː.mjʊ.lə.tɪv/', us_ipa: '/ˈkjuː.mjʊ.leɪ.t̬ɪv/' },
    { word: 'deliberate',   translation: 'deliberado',   category: 'adjectives', uk_ipa: '/dɪˈlɪb.ər.ɪt/',  us_ipa: '/dɪˈlɪb.ɚ.ɪt/' },
    { word: 'eloquent',     translation: 'elocuente',    category: 'adjectives', uk_ipa: '/ˈel.ə.kwənt/',    us_ipa: '/ˈel.ə.kwənt/' },
    { word: 'explicit',     translation: 'explícito',    category: 'adjectives', uk_ipa: '/ɪkˈsplɪs.ɪt/',   us_ipa: '/ɪkˈsplɪs.ɪt/' },
    { word: 'implicit',     translation: 'implícito',    category: 'adjectives', uk_ipa: '/ɪmˈplɪs.ɪt/',    us_ipa: '/ɪmˈplɪs.ɪt/' },
    { word: 'inherent',     translation: 'inherente',    category: 'adjectives', uk_ipa: '/ɪnˈhɪər.ənt/',    us_ipa: '/ɪnˈhɪr.ənt/' },
    { word: 'pertinent',    translation: 'pertinente',   category: 'adjectives', uk_ipa: '/ˈpɜː.tɪ.nənt/',   us_ipa: '/ˈpɝː.tɪ.nənt/' },
    { word: 'pragmatic',    translation: 'pragmático',   category: 'adjectives', uk_ipa: '/præɡˈmæt.ɪk/',   us_ipa: '/præɡˈmæt̬.ɪk/' },
    { word: 'subtle',       translation: 'sutil',        category: 'adjectives', uk_ipa: '/ˈsʌb.tl/',        us_ipa: '/ˈsʌb.tl/' },
    // Advanced nouns
    { word: 'analogy',      translation: 'analogía',     category: 'academic',  uk_ipa: '/əˈnæl.ə.dʒi/',    us_ipa: '/əˈnæl.ə.dʒi/' },
    { word: 'autonomy',     translation: 'autonomía',    category: 'general',   uk_ipa: '/ɔːˈtɒn.ə.mi/',    us_ipa: '/ɔːˈtɑː.nə.mi/' },
    { word: 'correlation',  translation: 'correlación',  category: 'academic',  uk_ipa: '/ˌkɒr.əˈleɪ.ʃən/', us_ipa: '/ˌkɔːr.əˈleɪ.ʃən/' },
    { word: 'credibility',  translation: 'credibilidad', category: 'general',   uk_ipa: '/ˌkred.ɪˈbɪl.ɪ.ti/', us_ipa: '/ˌkred.ɪˈbɪl.ɪ.ti/' },
    { word: 'discrepancy',  translation: 'discrepancia', category: 'general',   uk_ipa: '/dɪˈskrep.ən.si/', us_ipa: '/dɪˈskrep.ən.si/' },
    { word: 'integrity',    translation: 'integridad',   category: 'general',   uk_ipa: '/ɪnˈteɡ.rɪ.ti/',   us_ipa: '/ɪnˈteɡ.rɪ.ti/' },
    { word: 'manifestation', translation: 'manifestación', category: 'general', uk_ipa: '/ˌmæn.ɪ.fesˈteɪ.ʃən/', us_ipa: '/ˌmæn.ɪ.fesˈteɪ.ʃən/' },
    { word: 'nuance',       translation: 'matiz',        category: 'general',   uk_ipa: '/ˈnjuː.ɑːns/',     us_ipa: '/ˈnuː.ɑːns/' },
    { word: 'paradigm',     translation: 'paradigma',    category: 'academic',  uk_ipa: '/ˈpær.ə.daɪm/',    us_ipa: '/ˈper.ə.daɪm/' },
    { word: 'perseverance', translation: 'perseverancia', category: 'general',  uk_ipa: '/ˌpɜː.sɪˈvɪər.əns/', us_ipa: '/ˌpɝː.sɪˈvɪr.əns/' },
    { word: 'resilience',   translation: 'resiliencia',  category: 'general',   uk_ipa: '/rɪˈzɪl.i.əns/',   us_ipa: '/rɪˈzɪl.i.əns/' },
    { word: 'versatility',  translation: 'versatilidad', category: 'general',   uk_ipa: '/ˌvɜː.səˈtɪl.ɪ.ti/', us_ipa: '/ˌvɝː.səˈtɪl.ɪ.ti/' },
  ],

  C2: [
    { word: 'acrimony',     translation: 'acrimonia',    category: 'general',   uk_ipa: '/ˈæk.rɪ.mə.ni/',   us_ipa: '/ˈæk.rɪ.moʊ.ni/' },
    { word: 'alacrity',     translation: 'prontitud',    category: 'general',   uk_ipa: '/əˈlæk.rɪ.ti/',    us_ipa: '/əˈlæk.rɪ.ti/' },
    { word: 'ameliorate',   translation: 'mejorar',      category: 'verbs',     uk_ipa: '/əˈmiː.li.ə.reɪt/', us_ipa: '/əˈmiː.li.ɚ.eɪt/' },
    { word: 'anachronism',  translation: 'anacronismo',  category: 'general',   uk_ipa: '/əˈnæk.rə.nɪ.zəm/', us_ipa: '/əˈnæk.rə.nɪ.zəm/' },
    { word: 'assiduous',    translation: 'asiduo',       category: 'adjectives', uk_ipa: '/əˈsɪd.ju.əs/',    us_ipa: '/əˈsɪdʒ.u.əs/' },
    { word: 'burgeon',      translation: 'proliferar',   category: 'verbs',     uk_ipa: '/ˈbɜː.dʒən/',       us_ipa: '/ˈbɝː.dʒən/' },
    { word: 'capricious',   translation: 'caprichoso',   category: 'adjectives', uk_ipa: '/kəˈprɪʃ.əs/',    us_ipa: '/kəˈprɪʃ.əs/' },
    { word: 'catharsis',    translation: 'catarsis',     category: 'general',   uk_ipa: '/kəˈθɑː.sɪs/',     us_ipa: '/kəˈθɑːr.sɪs/' },
    { word: 'commensurate', translation: 'proporcional', category: 'adjectives', uk_ipa: '/kəˈmen.sjʊ.rɪt/', us_ipa: '/kəˈmen.sɚ.ɪt/' },
    { word: 'corroborate',  translation: 'corroborar',   category: 'verbs',     uk_ipa: '/kəˈrɒb.ə.reɪt/',  us_ipa: '/kəˈrɑː.bɚ.eɪt/' },
    { word: 'dichotomy',    translation: 'dicotomía',    category: 'general',   uk_ipa: '/daɪˈkɒt.ə.mi/',   us_ipa: '/daɪˈkɑː.t̬ə.mi/' },
    { word: 'ebullient',    translation: 'entusiasta',   category: 'adjectives', uk_ipa: '/ɪˈbʌl.i.ənt/',   us_ipa: '/ɪˈbʌl.i.ənt/' },
    { word: 'ephemeral',    translation: 'efímero',      category: 'adjectives', uk_ipa: '/ɪˈfem.ər.əl/',   us_ipa: '/ɪˈfem.ɚ.əl/' },
    { word: 'equivocate',   translation: 'equivocar',    category: 'verbs',     uk_ipa: '/ɪˈkwɪv.ə.keɪt/', us_ipa: '/ɪˈkwɪv.ə.keɪt/' },
    { word: 'esoteric',     translation: 'esotérico',    category: 'adjectives', uk_ipa: '/ˌes.əˈter.ɪk/',  us_ipa: '/ˌes.əˈter.ɪk/' },
    { word: 'hegemony',     translation: 'hegemonía',    category: 'general',   uk_ipa: '/hɪˈdʒem.ə.ni/',   us_ipa: '/hɪˈdʒem.ə.ni/' },
    { word: 'iconoclast',   translation: 'iconoclasta',  category: 'general',   uk_ipa: '/aɪˈkɒn.ə.klæst/', us_ipa: '/aɪˈkɑː.nə.klæst/' },
    { word: 'laconic',      translation: 'lacónico',     category: 'adjectives', uk_ipa: '/ləˈkɒn.ɪk/',     us_ipa: '/ləˈkɑː.nɪk/' },
    { word: 'loquacious',   translation: 'locuaz',       category: 'adjectives', uk_ipa: '/ləˈkweɪ.ʃəs/',   us_ipa: '/loʊˈkweɪ.ʃəs/' },
    { word: 'mendacious',   translation: 'mendaz',       category: 'adjectives', uk_ipa: '/menˈdeɪ.ʃəs/',   us_ipa: '/menˈdeɪ.ʃəs/' },
    { word: 'mitigate',     translation: 'mitigar',      category: 'verbs',     uk_ipa: '/ˈmɪt.ɪ.ɡeɪt/',    us_ipa: '/ˈmɪt̬.ɪ.ɡeɪt/' },
    { word: 'munificent',   translation: 'munificente',  category: 'adjectives', uk_ipa: '/mjuːˈnɪf.ɪ.sənt/', us_ipa: '/mjuːˈnɪf.ɪ.sənt/' },
    { word: 'obfuscate',    translation: 'ofuscar',      category: 'verbs',     uk_ipa: '/ˈɒb.fʌ.skeɪt/',   us_ipa: '/ˈɑːb.fʌ.skeɪt/' },
    { word: 'onerous',      translation: 'oneroso',      category: 'adjectives', uk_ipa: '/ˈəʊ.nər.əs/',    us_ipa: '/ˈoʊ.nɚ.əs/' },
    { word: 'paucity',      translation: 'escasez',      category: 'general',   uk_ipa: '/ˈpɔː.sɪ.ti/',     us_ipa: '/ˈpɔː.sɪ.ti/' },
    { word: 'pedantic',     translation: 'pedante',      category: 'adjectives', uk_ipa: '/pɪˈdæn.tɪk/',    us_ipa: '/pɪˈdæn.t̬ɪk/' },
    { word: 'perfidious',   translation: 'pérfido',      category: 'adjectives', uk_ipa: '/pəˈfɪd.i.əs/',   us_ipa: '/pɚˈfɪd.i.əs/' },
    { word: 'perspicacious', translation: 'perspicaz',   category: 'adjectives', uk_ipa: '/ˌpɜː.spɪˈkeɪ.ʃəs/', us_ipa: '/ˌpɝː.spɪˈkeɪ.ʃəs/' },
    { word: 'recalcitrant', translation: 'recalcitrante', category: 'adjectives', uk_ipa: '/rɪˈkæl.sɪ.trənt/', us_ipa: '/rɪˈkæl.sɪ.trənt/' },
    { word: 'reticent',     translation: 'reticente',    category: 'adjectives', uk_ipa: '/ˈret.ɪ.sənt/',    us_ipa: '/ˈret̬.ɪ.sənt/' },
    { word: 'salient',      translation: 'destacado',    category: 'adjectives', uk_ipa: '/ˈseɪ.li.ənt/',   us_ipa: '/ˈseɪ.li.ənt/' },
    { word: 'sanguine',     translation: 'optimista',    category: 'adjectives', uk_ipa: '/ˈsæŋ.ɡwɪn/',     us_ipa: '/ˈsæŋ.ɡwɪn/' },
    { word: 'spurious',     translation: 'espurio',      category: 'adjectives', uk_ipa: '/ˈspjʊər.i.əs/',  us_ipa: '/ˈspjʊr.i.əs/' },
    { word: 'taciturn',     translation: 'taciturno',    category: 'adjectives', uk_ipa: '/ˈtæs.ɪ.tɜːn/',   us_ipa: '/ˈtæs.ɪ.tɝːn/' },
    { word: 'tenacious',    translation: 'tenaz',        category: 'adjectives', uk_ipa: '/tɪˈneɪ.ʃəs/',    us_ipa: '/tɪˈneɪ.ʃəs/' },
    { word: 'ubiquitous',   translation: 'ubicuo',       category: 'adjectives', uk_ipa: '/juːˈbɪk.wɪ.təs/', us_ipa: '/juːˈbɪk.wɪ.t̬əs/' },
    { word: 'vacuous',      translation: 'vacuo',        category: 'adjectives', uk_ipa: '/ˈvæk.ju.əs/',    us_ipa: '/ˈvæk.ju.əs/' },
    { word: 'veracious',    translation: 'veraz',        category: 'adjectives', uk_ipa: '/vəˈreɪ.ʃəs/',    us_ipa: '/vəˈreɪ.ʃəs/' },
    { word: 'volatile',     translation: 'volátil',      category: 'adjectives', uk_ipa: '/ˈvɒl.ə.taɪl/',   us_ipa: '/ˈvɑː.lɪ.t̬əl/' },
    { word: 'propitious',   translation: 'propicio',     category: 'adjectives', uk_ipa: '/prəˈpɪʃ.əs/',    us_ipa: '/prəˈpɪʃ.əs/' },
  ]
};

// Helper functions
function getWordsForLevel(level) {
  return VOCABULARY[level] || [];
}

function getWordsForLevelAndCategory(level, category) {
  const words = getWordsForLevel(level);
  if (category === 'all') return words;
  return words.filter(w => w.category === category);
}

function getCategoriesForLevel(level) {
  const words = getWordsForLevel(level);
  const cats = [...new Set(words.map(w => w.category))].sort();
  return ['all', ...cats];
}

function getAllWords(level) {
  if (level === 'all') {
    return Object.values(VOCABULARY).flat();
  }
  return getWordsForLevel(level);
}
