'use strict';
const fs   = require('fs');
const path = require('path');
const Database = require('better-sqlite3');

const ROOT     = path.join(__dirname, '..');
const DB_PATH  = path.join(ROOT, 'data', 'voc.db');
const HOF_FILE = path.join(ROOT, 'data', 'hof.json');

// Ensure schema exists
require('./setup-db');

// Use vocabulary-full.json if available (generated by fetch-vocab.js), else vocabulary.js
let VOCABULARY;
const fullVocab = path.join(ROOT, 'data', 'vocabulary-full.json');
if (fs.existsSync(fullVocab)) {
  VOCABULARY = JSON.parse(fs.readFileSync(fullVocab, 'utf8'));
  console.log('[seed] Usando vocabulary-full.json');
} else {
  const vocSrc  = fs.readFileSync(path.join(ROOT, 'js', 'vocabulary.js'), 'utf8');
  const tmpFile = path.join(__dirname, '_tmp_vocab.js');
  fs.writeFileSync(tmpFile, vocSrc + '\nmodule.exports = { VOCABULARY };\n');
  try {
    ({ VOCABULARY } = require(tmpFile));
  } finally {
    fs.unlinkSync(tmpFile);
  }
  console.log('[seed] Usando vocabulary.js (base de 350 palabras)');
}

const db = new Database(DB_PATH);

// Clear existing words to avoid duplicates on re-run
db.prepare('DELETE FROM words').run();

const insertWord = db.prepare(`
  INSERT INTO words (word, translation, level, category, uk_ipa, us_ipa)
  VALUES (@word, @translation, @level, @category, @uk_ipa, @us_ipa)
`);

const seedWords = db.transaction(() => {
  let total = 0;
  for (const [level, words] of Object.entries(VOCABULARY)) {
    for (const w of words) insertWord.run({ ...w, level });
    console.log(`[seed] ${level}: ${words.length} palabras`);
    total += words.length;
  }
  return total;
});

const totalWords = seedWords();
console.log(`[seed] Total palabras insertadas: ${totalWords}`);

// Migrate HoF if file exists and hof table is empty
const hofCount = db.prepare('SELECT COUNT(*) as n FROM hof').get().n;
if (hofCount === 0 && fs.existsSync(HOF_FILE)) {
  const hof = JSON.parse(fs.readFileSync(HOF_FILE, 'utf8'));
  const insertHof = db.prepare(`
    INSERT INTO hof (name, level, mode, challenge, category, score, correct, total, date)
    VALUES (@name, @level, @mode, @challenge, @category, @score, @correct, @total, @date)
  `);
  const seedHof = db.transaction((entries) => {
    for (const e of entries) insertHof.run({
      name:      e.name      || '',
      level:     e.level     || '',
      mode:      e.mode      || '',
      challenge: e.challenge || '',
      category:  e.category  || '',
      score:     e.score     || 0,
      correct:   e.correct   || 0,
      total:     e.total     || 0,
      date:      e.date      || '',
    });
  });
  seedHof(hof);
  console.log(`[seed] HoF: ${hof.length} entradas migradas`);
} else if (hofCount > 0) {
  console.log(`[seed] HoF: ya tiene ${hofCount} entradas, omitiendo`);
}

db.close();
console.log('[seed] Completado:', DB_PATH);
